name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      build-command:
        description: The command to run to build the project
        type: string
        required: true
      output-path:
        description: Path to the build output directory
        type: string
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Setup GitHub Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Build command
        shell: bash
        run: ${{ inputs.build-command }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ${{ inputs.output-path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
