name: Publish Node.js and pnpm
description: This workflow handles the publish process for Node.js and pnpm projects.

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./checkout-repository

      - name: Setup environment
        uses: ./setup-node-pnpm
        with:
          registry-url: https://registry.npmjs.org
          scope: "@sehv-oss"

      - name: Run build
        run: pnpm build

      - name: Changesets publish
        uses: ./changesets
        with:
          publish-command: pnpm changeset:publish
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-token: ${{ secrets.NPM_TOKEN }}
