name: Pull Request Node.js and pnpm
description: A GitHub Actions workflow to build, lint and test a Node.js project using pnpm when a pull request is opened or updated. The workflow checks out the repository, sets up the Node.js environment with pnpm, and runs the build, lint and test scripts defined in package.json.

on:
  workflow_call:
    inputs:
      cspell:
        description: Whether CSpell should be run
        type: boolean
        default: true
        required: false
      prettier:
        description: Whether Prettier should be run
        type: boolean
        default: true
        required: false
      eslint:
        description: Whether ESLint should be run
        type: boolean
        default: true
        required: false
      test:
        description: Whether tests should be run
        type: boolean
        default: true
        required: false
      test-setup:
        description: Whether the test environment should be set up before running tests
        type: boolean
        default: true
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Run build
        run: pnpm build

  lint:
    name: Lint
    needs: build
    if: ${{ inputs.cspell || inputs.prettier || inputs.eslint }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Run lints
        uses: sehv-oss/actions/lint-pnpm@main
        with:
          cspell: ${{ inputs.cspell }}
          prettier: ${{ inputs.prettier }}
          eslint: ${{ inputs.eslint }}

  test:
    name: Test
    needs: build
    if: ${{ inputs.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Setup and run tests
        uses: sehv-oss/actions/test-pnpm@main
        with:
          test-setup: ${{ inputs.test-setup }}
