name: Release Node.js and pnpm
description: This workflow handles the release process for Node.js and pnpm projects.

on:
  workflow_call:
    inputs:
      cspell:
        description: Whether CSpell should be run
        type: boolean
        default: true
        required: false
      prettier:
        description: Whether Prettier should be run
        type: boolean
        default: true
        required: false
      eslint:
        description: Whether ESLint should be run
        type: boolean
        default: true
        required: false
      skip-test:
        description: Whether tests should be skipped
        type: boolean
        default: false
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Run build
        run: pnpm build

  lint:
    name: Lint
    needs: build
    if: ${{ inputs.cspell || inputs.prettier || inputs.eslint }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Run lints
        uses: sehv-oss/actions/lint-pnpm@main
        with:
          cspell: ${{ inputs.cspell }}
          prettier: ${{ inputs.prettier }}
          eslint: ${{ inputs.eslint }}

  test:
    name: Test
    needs: build
    if: ${{ !inputs.skip-test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Setup and run tests
        uses: sehv-oss/actions/test-pnpm@main

  release:
    name: Release
    needs: [build, lint, test]
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main
        with:
          registry-url: https://registry.npmjs.org
          scope: "@sehv-oss"

      - name: Changesets version
        uses: sehv-oss/actions/changesets@main
        with:
          version-command: pnpm changeset:version
          github-token: ${{ secrets.GITHUB_TOKEN }}
