name: Release Node.js and pnpm
description: This workflow handles the release process for Node.js and pnpm projects.

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Run build
        run: pnpm build

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Run lints
        uses: sehv-oss/actions/lint-pnpm@main

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main

      - name: Setup and Run tests
        uses: sehv-oss/actions/test-pnpm@main

  release:
    name: Release
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: sehv-oss/actions/checkout-repository@main

      - name: Setup environment
        uses: sehv-oss/actions/setup-node-pnpm@main
        with:
          registry-url: https://registry.npmjs.org
          scope: '@sehv-oss'

      - name: Release
        uses: sehv-oss/actions/changesets-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-token: ${{ secrets.NPM_TOKEN }}
          publish-command: pnpm changeset publish
          version-command: pnpm changeset version
